name: 'PR Ready for Review'
description: 'Labels PRs that are ready review'
inputs:
  token:
    description: 'A token used to access the Github API.  Usually {{ secrets.GITHUB_TOKEN }}'
    required: true
  verbose:
    description: 'If "true" then output verbose details about what is being checked'
    required: false
    default: ''
runs:
  using: 'node12'
  main: 'index.js'
