on:
  check_suite:
    types: [completed]
  issue_comment:

jobs:
  main_job:
    runs-on: ubuntu-latest
    name: Label PR with review status
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Label PR if appropriate
        uses: ./ # Uses an action in the root directory
        id: label-pr
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
