on:
  [pull_request]

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: Run tests
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v2
      - name: Run tests
        uses: ./test-check # Uses an action in the root directory
        id: test-pr
        with:
          dummyRepoOwner: 'westonpace'
          dummyRepoName: 'pr-needs-review-dummy-repo'
          dummyRepoToken: ${{ secrets.GITHUB_TOKEN }}
          dummyRepoAltToken: ${{ secrets.DUMMY_REPO_TOKEN }}
